### PR TITLE
🐛🛡️  Protected Load Order File Handling

### LINKED ISSUE #346: Load Order Reset, Unable to Parse Stored LO
For some reason, it's possible to run into a condition where the stored load order can't be read, which means it gets discarded.

image

Unsure about the cause, could be a race condition either on write or on read (new LO being written while current being read.)

Several mitigations:

- [ ] Cancel and show error when load order present but can't be read - user can then manually delete if needed, and we don't destroy the file
- [ ] Write to a tempfile and rename only when fully written (which is just good practice..), although it's possible this won't solve issue 
- [ ] Use a lockfile
- [ ] Store file we failed to parse so it can be examined (but the error cancel is probably better)
- [ ] Store N previous load orders (log rotation is a pain though)
- [ ] Actually try to show some kind of error from the decoder

### PR DESCRIPTION
**Pull request by effs**
## Exec Smry: Fixy the bug and add the protecc

🛡️ Protect load order from being overwritten in transient/persistent error cases
🐛 Separate handling for no LO file (ok) and unable to decode existing file (nok)
🐛 User has to manually fix an invalid LO file

🛡️ Writing LO to disk uses a tempfile to avoid possible race conditions from multiple deployments

📰 (Slightly) better errors from splitting `stat` for dir and actual file ops, plus dialog/notif

Closes #346 and #351

### CODE REVIEW

File: src/load_order.ts [hunk 1]
```diff
@@ -212,42 +219,41 @@ export const loadOrderUsageInstructionsForVortexGui =
...
+          decodeLoadOrder(content),
+          fromEitherTE,
+          mapLeftTE((error) =>
+            new Error(`Couldn't decode load order file: ${error.message}`)),
+          mapTE((loadOrder) => {
+            vortexApi.log(`info`, `${me}: Successfully deserialized load order id: ${Date.parse(loadOrder.generatedAt)} (${loadOrder.generatedAt})`);
+            vortexApi.log(`debug`, `${me}: Current stored load order deserialized: ${S(loadOrder)}`);
+            return loadOrder.entriesInOrderWithEarlierWinning;
+          }),
+        )),
```
Comment (effs) [inline src/load_order.ts:241]: This may warrant additional context: the first error is recoverable, the second isn't.

I failed to come up with a good way to handle that\*, so the `swap` turns the error into a default success and the `orElse` replaces the 'error' with a normal `[Task]Either`.

\* I guess cleanest would've been to write a blank LO but that's just no.

File: src/load_order.ts [hunk 2]
```diff
@@ -355,14 +361,25 @@ const compileDetesToGenerateLoadOrderUi: VortexWrappedDeserializeFunc = async (
...
+
+  // The rest of this function could and should be refactored into a pipeline
+  // to get rid of this early return
+
+  if (isLeft(deserializedLoadOrder)) {
+    vortexApi.log(`error`, `${me}: Error deserializing load order: ${deserializedLoadOrder.left.message}`);
+    showInvalidLoadOrderFileErrorDialog(vortexApi, loadOrderPathFor(activeProfile, gameDirPath));
+
+    return Promise.reject(deserializedLoadOrder.left);
+  }
```
Comment (E1337Kat) [inline src/load_order.ts:379]: Will this promise rejection stop complete crashes at the very least?

File: src/load_order.ts (hunk 1 above)
Comment (E1337Kat) [reply src/load_order.ts:241]: I guess it is good enough for now. There is a lot of refactoring that can be done all over... _eventually_.

**Review by E1337Kat — APPROVED** [review]
I think it looks good. any thing that helps stability is a good idea.

File: src/load_order.ts (hunk 2 above)
Comment (effs) [reply src/load_order.ts:379]: Nothing fully crashes, it's just hard to interpret, but most importantly this will prevent overwriting the file in case the decoding failure was because of a race condition.
