### PR TITLE
Bug/ellie/redscript failure 139

### LINKED ISSUE #106: Only Show Files In Dialogs, Not The Directories
Since it's just the files that are relevant, only show those in the file listing.

### LINKED ISSUE #139: Redscript Mod With Basedir And Canonical Prompting Unnecessarily
Mod: [StreetStyle](https://www.nexusmods.com/cyberpunk2077/mods/2975?tab=files)

Layout: 
image

In this case the 'extra' files are actually intended to delete the old installation style, but I'm not sure this should fail anyway.

### PR DESCRIPTION
**Pull request by E1337Kat**
closes #139 
closes #106

### CODE REVIEW

**Comment by E1337Kat** [comment]
closes #139 
closes #106

File: src/installer.redscript.ts [hunk 1]
```diff
@@ -73,6 +74,39 @@ export const redscriptBasedirLayout = (
   };
 };
 
+export const detectRedscriptToplevelLayout = (fileTree: FileTree): boolean =>
+  dirWithSomeIn(FILETREE_ROOT, matchRedscript, fileTree);
+
+export const redscriptToplevelLayout = (
```
Comment (effs) [inline src/installer.redscript.ts:80]: 💎

File: src/installer.redscript.ts [hunk 2]
```diff
@@ -145,68 +179,51 @@ export const testForRedscriptMod: VortexWrappedTestSupportedFunc = (
...
-  const hasBasedirReds = dirWithSomeIn(
-    REDS_MOD_CANONICAL_PATH_PREFIX,
-    matchRedscript,
+  const allInstructionSets: LayoutToInstructions[] = [
+    redscriptToplevelLayout,
+    redscriptBasedirLayout,
+    redscriptCanonLayout,
+  ];
+
+  const allInstructionsPerLayout = useAllMatchingLayouts(
```
Comment (effs) [inline src/installer.redscript.ts:198]: `useAllMatchingLayouts` works right for the canon + base case because they are exclusive themselves, but toplevel will match with both of them, I think? Not that that's likely to be an issue in practice, but you could use `useFirstMatchingLayoutForInstructions` to ensure only the first match is picked (or then make toplevel layout exclusive too).

(And I guess those two should either both be with `ForInstructions` or not, but :P)

**Review by effs — APPROVED** [review]

File: src/installer.redscript.ts (hunk 2 above)
Comment (E1337Kat) [reply src/installer.redscript.ts:200]: going with a simple solution here. generally I don't think the case of a topLevel with the other two will ever come up, but eh... might as well be safe than sorry.
