### PR TITLE
CET Mod Installation Fixes

### LINKED ISSUE #13: Support CET Mods
If a CET mod doesn't adhere to conventions, either reject it or fix it the rest of the way.

Need to at least:

- [ ] Ensure it's [bin/../]somename/init.lua so that we can correctly put it in the CET folder
- [ ] Allow init.lua in subfolders of the mod

Optional, maybe later:

- [ ] Allow mod to just have the mod at top level, and place it in CET/mods/MODNAME/

### PR DESCRIPTION
**Pull request by effs**
Installer for CET mods.

Other:

- Installers prioritized based on array position now

Closes #13

### CODE REVIEW

File: src/installers.ts [hunk 1]
```diff
@@ -643,19 +682,103 @@ const byPriority = (a: Installer, b: Installer) => a.priority - b.priority;
...
     id: "cp2077-standard-mod",
-    priority: 31,
-    testSupported: modHasBadStructure,
-    install: installWithCorrectedStructure,
+    testSupported: testAnyOtherModFallback,
+    install: installAnyModWithBasicFixes,
+  },
+  {
+    type: InstallerType.NotSupported,
+    id: "cp2077-standard-mod",
```
Comment (E1337Kat) [inline src/installers.ts:780]: Pretty sure the id needs to be unique, even if the whole purpose of this step is to fail.

File: src/installers.ts [hunk 2]
```diff
@@ -643,19 +682,103 @@ const byPriority = (a: Installer, b: Installer) => a.priority - b.priority;
...
+    install: notInstallableMod,
+  },
+  */
   {
     type: InstallerType.ArchiveOnly,
     id: "cp2077-basic-archive-mod",
-    priority: 30,
-    testSupported: modWithArchiveOnly,
-    install: archiveOnlyInstaller,
+    testSupported: testForArchiveOnlyMod,
```
Comment (E1337Kat) [inline src/installers.ts:769]: The fallback installer might should be a straight copy from source to destination. This would be the case only if the game being modded is the game the mod is for (based on the given information) and no higher priority installers fit. I think this would be an ideal fallback for most unsupported mods.

File: src/installers.ts [hunk 3]
```diff
@@ -77,20 +72,56 @@ const REDSCRIPT_FILE_EXT = ".reds";
...
+  priority: number;
+}
+
+// testSupported that always fails
+//
+export const notSupportedModType: Vortex.TestSupported = (
+  _files: string[],
+  _gameId: string,
+): Promise<Vortex.ISupportedResult> =>
+  Promise.resolve({ supported: false, requiredFiles: [] });
```
Comment (E1337Kat) [inline src/installers.ts:113]: I guess we don't need to even bother testing the game if this TestSupported always resolves to not be used.

**Review by E1337Kat — COMMENTED** [review]
Will need to do a test in actual to see if the same id on installers is okay or not. I can run that sanity check later after work or you can if you want. As long as that is okay, then this is good to merge, I would say.

File: src/installers.ts (hunk 1 above)
Comment (effs) [reply src/installers.ts:780]: Yep, it should!

File: src/installers.ts (hunk 2 above)
Comment (effs) [reply src/installers.ts:769]: I’ll add a follow-up PR for this.
